#!/usr/bin/env bash
# Displays information about subdomains

display_info() {
    local domain=$1
    local subdomain=$2
    
    # Using dig to query DNS information and awk to format the output
    local line=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1)
    local record_type=$(echo "$line" | awk '{print $4}')
    local destination=$(echo "$line" | awk '{print $5}')
    
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script logic
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    # If no subdomain is specified, display info for default subdomains
    display_info "$domain" "www"
    display_info "$domain" "lb-01"
    display_info "$domain" "web-01"
    display_info "$domain" "web-02"
else
    # Display info for the specified subdomain
    display_info "$domain" "$subdomain"
fi
